apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-client-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: ''
  resources:
    requests:
      storage: 500Gi
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      volume: nfs-client-pv
