apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "nfs-client-provisioner.fullname" . }}-pv
  namespace: {{ .Release.Namespace }}
  labels:
    nfs-client-provisioner: {{ template "nfs-client-provisioner.fullname" . }}
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storageClass.mountOptions }}
  mountOptions:
    {{- range .Values.storageClass.mountOptions }}
    - {{ . }}
    {{- end }}
  {{- end }}
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
