apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-client-pv
  namespace: {{ .Release.Namespace }}
  labels:
    volume: nfs-client-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  mountOptions: {{ .Values.storageClass.mountOptions }}
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
