apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "nfs-client-provisioner.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: ''
  resources:
    requests:
      storage: 10Mi
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      nfs-client-provisioner: {{ template "nfs-client-provisioner.fullname" . }}
